kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: cj-countdown
spec:
  # minuto, hora, dia del mes, dia de la semana y mes
  schedule: "2 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cj-counter
            image: alpine
            command:
            - "bin/sh"
            - "-c"
            - "for i in 9 8 7 6 5 4 3 2 1 ; do echo $i ; done"
          restartPolicy: OnFailure

