apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: hello-world.info
    http:
      paths:
      - path: /
        backend:
          serviceName: web1-svc
          servicePort: 8080
      - path: /v2/*
        backend:
          serviceName: web2-svc
          servicePort: 8080

