kind: Job
apiVersion: batch/v1
metadata:
  name: countdown-pl
spec:
  # completions like replicas
  completions: 6
  parallelism: 2
  template:
    metadata:
      name: countdown-pl
    spec:
      containers:
      - name: counter
        image: alpine
        command:
         - "bin/sh"
         - "-c"
         - "for i in 9 8 7 6 5 4 3 2 1 ; do echo $i ; done"
      restartPolicy: Never

