kind: Deployment 
apiVersion: apps/v1 
metadata: 
  name: nginx-dp 
spec: 
  replicas: 5 
  strategy: 
    type: RollingUpdate 
    rollingUpdate: 
      maxSurge: 2 
      maxUnavailable: 1 
  selector: 
    matchLabels: 
      app: nginx 
  template: 
    metadata: 
      labels: 
        app: nginx 
    spec: 
      containers: 
      - name: nginx 
        #image: mario21ic/nginx:v1.1
        #image: mario21ic/nginx:v1.2 
        image: mario21ic/nginx:v1.3 
        ports: 
        - containerPort: 80 
          name: http 
          protocol: TCP 
