kind: Deployment 
apiVersion: apps/v1 
metadata: 
  name: nginx-dp 
spec: 
  replicas: 2 
  selector: 
    matchLabels: 
      app: nginx 
  template: 
    metadata: 
      labels: 
        app: nginx 
    spec: 
      containers: 
      - name: nginx 
        image: mario21ic/nginx:v1.1 
        ports: 
        - containerPort: 80 
          name: http 
          protocol: TCP 
