kind: Pod 
apiVersion: v1 
metadata: 
  name: multi-pod 
spec: 
  containers: 
  - name: nginx 
    image: nginx:alpine 
    ports: 
    - containerPort: 80 
      name: http 
      protocol: TCP 
  - name: alpine 
    image: alpine:latest 
    command: ["/bin/sh"] 
    args: ["-c", "while true; do date; sleep 5; done"] 
