kind: Pod  
apiVersion: v1  
metadata:  
  name: pod-cpu-demo  
spec:  
  containers:  
  - name: pod-cpu-demo-ctr  
    image: vish/stress  
    args:  
    - -cpus  
    - "2"  
    resources:  
      requests:  
        cpu: "0.5"  
      limits:  
        cpu: "1" 
