kind: Pod 
apiVersion: v1 
metadata: 
  name: web-pod 
spec: 
  containers: 
    - name: nginx 
      image: nginx:alpine 
      ports: 
      - containerPort: 80 
        name: http 
        protocol: TCP  
