apiVersion: v1
kind: Service
metadata:
  name: hpa-example-svc
  labels:
    app: hpa-example
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: http-port
    protocol: TCP
  selector:
    app: hpa-example
