kind: Deployment
apiVersion: apps/v1
metadata:
  name: dp-readiness
spec:
  selector:
    matchLabels:
      app: python
  replicas: 2
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: web
        image: mario21ic/readiness-liveness:v1
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          periodSeconds: 2
          initialDelaySeconds: 6
          timeoutSeconds: 3
          failureThreshold: 3
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /live
            port: 8080
          periodSeconds: 2
          initialDelaySeconds: 6
          timeoutSeconds: 2
          failureThreshold: 3
          successThreshold: 1
        ports:
          - name: web
            containerPort: 8080
            protocol: TCP

