kind: Deployment
apiVersion: apps/v1
metadata:
  name: dp-liveness
spec:
  selector:
    matchLabels:
      app: python
  replicas: 2
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: web
        image: mario21ic/readiness-liveness:v1
        livenessProbe:
          httpGet:
            path: /error
            #path: /live
            port: 8080
          periodSeconds: 1
          initialDelaySeconds: 6
          timeoutSeconds: 2
          failureThreshold: 2
          successThreshold: 1
        ports:
          - name: web
            containerPort: 80
            protocol: TCP

