kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-dep
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: myfile
          configMap:
            name: myconfigdata
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: myfile
              mountPath: /mnt/files/

