kind: Pod
apiVersion: v1
metadata:
  name: pod-secret-file
spec:
  volumes:
    - name: myfile
      secret:
        secretName: my-secret
        items:
        - key: hello
          path: my-subdir/hello
  containers:
    - name: nginx
      image: nginx:alpine
      volumeMounts:
      - name: myfile
        mountPath: /mnt/files/
        readOnly: true

