kind: Pod
apiVersion: v1
metadata:
  name: pod-cm-file
spec:
  volumes:
    - name: myfile
      configMap:
        #name: nginx-cm
        name: myconfigdata
  containers:
    - name: nginx
      image: nginx:alpine
      volumeMounts:
      - name: myfile
        mountPath: /mnt/files/
        readOnly: true

