kind: Pod
apiVersion: v1
metadata:
  name: pod-secret-file-all
spec:
  volumes:
    - name: myvolumefile
      secret:
        secretName: my-secret
  containers:
    - name: nginx
      image: nginx:alpine
      volumeMounts:
      - name: myvolumefile
        mountPath: /mnt/files/

