kind: Service
apiVersion: v1
metadata:
  name: nginx-np-svc
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: web
      nodePort: 32002 # node
      port: 8080 # servicio interno
      targetPort: 80 # pod-container

