kind: Service
apiVersion: v1
metadata:
  name: nginx-np2-svc
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: http
      nodePort: 32002 # node
      port: 8080 # service interno
      targetPort: 80 # pod-container


