kind: Service
apiVersion: v1
metadata:
  name: nginx-np-readiness
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: web
      port: 80 # service interno
      targetPort: 80 # container

